# Generated by Django 3.0 on 2022-03-23 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('date_time_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время удаления')),
                ('existance_duration', models.DurationField(verbose_name='Время существования')),
                ('finish_date_deadline', models.DateField(verbose_name='Заданное время выполнения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('activity', models.BooleanField(default=True, verbose_name='Активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
