# Generated by Django 3.0 on 2022-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='existance_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Время существования'),
        ),
    ]
